\connect ecommerce_db

-- ============================================================
-- E-COMMERCE SOURCE DATABASE
-- ============================================================
-- Tables:
--   CUSTOMER
--   ONLINE_ORDER
--   ORDER_ITEM
--   RESERVATION
--
-- product_id and store_id refer to records owned by the
-- Inventory database, so cross-database foreign keys are not
-- enforced here.
-- ============================================================


-- ============================================================
-- CUSTOMER
-- ============================================================

CREATE TABLE IF NOT EXISTS customer (
    customer_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name   VARCHAR(100) NOT NULL,
    email           VARCHAR(150) NOT NULL UNIQUE
);


-- ============================================================
-- ONLINE ORDER
-- ============================================================

CREATE TABLE IF NOT EXISTS online_order (
    order_id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id             INT NOT NULL REFERENCES customer(customer_id),
    fulfilment_store_id     INT NOT NULL,
    order_status            VARCHAR(30) NOT NULL
        CHECK (order_status IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
    order_total             NUMERIC(10,2) NOT NULL
        CHECK (order_total >= 0),
    created_at              TIMESTAMP NOT NULL DEFAULT now(),
    updated_at              TIMESTAMP NOT NULL DEFAULT now()
);


-- ============================================================
-- ORDER ITEM
-- ============================================================

CREATE TABLE IF NOT EXISTS order_item (
    order_item_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INT NOT NULL REFERENCES online_order(order_id),
    product_id      INT NOT NULL,
    quantity        INT NOT NULL CHECK (quantity > 0),
    unit_price      NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0),
    line_amount     NUMERIC(10,2) NOT NULL CHECK (line_amount >= 0)
);


-- ============================================================
-- RESERVATION
-- ============================================================

CREATE TABLE IF NOT EXISTS reservation (
    reservation_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            INT NOT NULL REFERENCES online_order(order_id),
    product_id          INT NOT NULL,
    store_id            INT NOT NULL,
    quantity            INT NOT NULL CHECK (quantity > 0),
    reservation_status  VARCHAR(30) NOT NULL
        CHECK (reservation_status IN ('ACTIVE', 'CANCELLED', 'EXPIRED', 'RELEASED')),
    created_at          TIMESTAMP NOT NULL DEFAULT now(),
    expires_at          TIMESTAMP NULL,
    released_at         TIMESTAMP NULL
);


-- ============================================================
-- SYNTHETIC DATA
-- ============================================================

INSERT INTO customer
    (customer_id, customer_name, email)
VALUES
    (1, 'Customer A', 'customer.a@example.com'),
    (2, 'Customer B', 'customer.b@example.com'),
    (3, 'Customer C', 'customer.c@example.com')
ON CONFLICT (customer_id) DO NOTHING;


INSERT INTO online_order
(
    order_id,
    customer_id,
    fulfilment_store_id,
    order_status,
    order_total,
    created_at,
    updated_at
)
VALUES
    (1001, 1, 10, 'CONFIRMED', 79.99, now(), now()),
    (1002, 3, 20, 'COMPLETED', 149.99, now(), now()),
    (1003, 2, 10, 'CANCELLED', 59.99, now(), now())
ON CONFLICT (order_id) DO NOTHING;


INSERT INTO order_item
(
    order_item_id,
    order_id,
    product_id,
    quantity,
    unit_price,
    line_amount
)
VALUES
    (5001, 1001, 101, 1, 79.99, 79.99),
    (5002, 1002, 102, 1, 149.99, 149.99),
    (5003, 1003, 103, 1, 59.99, 59.99)
ON CONFLICT (order_item_id) DO NOTHING;


INSERT INTO reservation
(
    reservation_id,
    order_id,
    product_id,
    store_id,
    quantity,
    reservation_status,
    created_at,
    expires_at,
    released_at
)
VALUES
(
    9001,
    1001,
    101,
    10,
    1,
    'ACTIVE',
    now(),
    now() + INTERVAL '2 hours',
    NULL
),
(
    9002,
    1003,
    103,
    10,
    1,
    'CANCELLED',
    now() - INTERVAL '1 hour',
    now() + INTERVAL '1 hour',
    now()
)
ON CONFLICT (reservation_id) DO NOTHING;


-- ============================================================
-- VERIFY DATA
-- ============================================================

SELECT
    c.customer_name,
    o.order_id,
    o.order_status,
    o.fulfilment_store_id,
    oi.product_id,
    oi.quantity,
    r.reservation_id,
    r.store_id,
    r.reservation_status,
    r.released_at
FROM customer c
JOIN online_order o
    ON c.customer_id = o.customer_id
JOIN order_item oi
    ON o.order_id = oi.order_id
LEFT JOIN reservation r
    ON o.order_id = r.order_id
    AND oi.product_id = r.product_id
ORDER BY o.order_id;