\connect pos_db

-- store_id / product_id refer to the Inventory database (separate database, so no
-- enforced foreign key). POS never stores stock quantities: Inventory owns them.

CREATE TABLE IF NOT EXISTS pos_employee (
    employee_id    INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       INT           NOT NULL,
    employee_name  VARCHAR(100)  NOT NULL,
    employee_role  VARCHAR(50)   NOT NULL,
    active_flag    BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS pos_promotion (
    promotion_id    INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_code  VARCHAR(30)    NOT NULL UNIQUE,
    promotion_name  VARCHAR(100)   NOT NULL,
    discount_type   VARCHAR(20)    NOT NULL CHECK (discount_type IN ('PERCENT','FIXED_AMOUNT')),
    discount_value  NUMERIC(10,2)  NOT NULL CHECK (discount_value >= 0),
    start_date      DATE           NOT NULL,
    end_date        DATE           NOT NULL,
    active_flag     BOOLEAN        NOT NULL DEFAULT TRUE,
    CHECK (end_date >= start_date)
);

-- A sale ATTEMPT: rejected attempts are stored too (they feed FACT_POS_ACTIVITY)
CREATE TABLE IF NOT EXISTS pos_transaction (
    transaction_id         INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id               INT            NOT NULL,
    employee_id            INT            NOT NULL REFERENCES pos_employee (employee_id),
    transaction_timestamp  TIMESTAMP      NOT NULL DEFAULT now(),
    transaction_status     VARCHAR(20)    NOT NULL
        CHECK (transaction_status IN ('PENDING','APPROVED','REJECTED')),
    rejection_reason       VARCHAR(255)   NULL,
    total_amount           NUMERIC(10,2)  NOT NULL CHECK (total_amount >= 0),
    -- a rejected attempt must say why
    CONSTRAINT ck_rejection_reason
        CHECK (transaction_status <> 'REJECTED' OR rejection_reason IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS pos_transaction_item (
    transaction_item_id  INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id       INT            NOT NULL REFERENCES pos_transaction (transaction_id),
    product_id           INT            NOT NULL,
    promotion_id         INT            NULL REFERENCES pos_promotion (promotion_id),
    quantity             INT            NOT NULL CHECK (quantity > 0),
    unit_price           NUMERIC(10,2)  NOT NULL CHECK (unit_price >= 0),
    line_amount          NUMERIC(10,2)  NOT NULL CHECK (line_amount >= 0)
);

-- 0..N payments per transaction (none for a rejected attempt)
CREATE TABLE IF NOT EXISTS pos_payment (
    payment_id         INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id     INT            NOT NULL REFERENCES pos_transaction (transaction_id),
    payment_method     VARCHAR(20)    NOT NULL,
    payment_amount     NUMERIC(10,2)  NOT NULL CHECK (payment_amount >= 0),
    payment_status     VARCHAR(20)    NOT NULL,
    payment_timestamp  TIMESTAMP      NOT NULL DEFAULT now()
);

-- 0..1 receipt per transaction (only approved sales get one)
CREATE TABLE IF NOT EXISTS pos_receipts (
    receipt_id       INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id   INT          NOT NULL UNIQUE REFERENCES pos_transaction (transaction_id),
    receipt_number   VARCHAR(30)  NOT NULL UNIQUE,
    issued_at        TIMESTAMP    NOT NULL DEFAULT now(),
    delivery_method  VARCHAR(20)  NOT NULL
);

-- ---------------------------------------------------------------------------
-- POS sale check
-- Stock belongs to Inventory (inventory_db), so POS asks Inventory before approving a sale.
-- dblink lets this function run one query in inventory_db: sell_stock(...), which checks
-- Available-to-Sell (= on-hand - reserved) and takes the stock in one atomic step.
-- Needs: the Inventory owner's sell_stock function and a stock row for the product.
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS dblink;

CREATE OR REPLACE FUNCTION pos_attempt_sale(
    p_store_id INT, p_employee_id INT, p_product_id INT, p_quantity INT, p_unit_price NUMERIC)
RETURNS TABLE (out_transaction_id INT, out_status VARCHAR, out_reason VARCHAR)
LANGUAGE plpgsql AS $$
DECLARE
    v_txn_id  INT;
    v_total   NUMERIC(10,2) := p_quantity * p_unit_price;
    v_success BOOLEAN;
    v_reason  TEXT;
BEGIN
    -- 1. Record the attempt (rejected attempts are kept for the warehouse)
    INSERT INTO pos_transaction (store_id, employee_id, transaction_status, total_amount)
    VALUES (p_store_id, p_employee_id, 'PENDING', v_total)
    RETURNING pos_transaction.transaction_id INTO v_txn_id;

    INSERT INTO pos_transaction_item (transaction_id, product_id, quantity, unit_price, line_amount)
    VALUES (v_txn_id, p_product_id, p_quantity, p_unit_price, v_total);

    -- 2. Ask Inventory whether the sale is allowed (transaction_id is the idempotency key)
    SELECT r.success, r.reason INTO v_success, v_reason
    FROM dblink('dbname=inventory_db',
                format('SELECT success, reason FROM sell_stock(%s, %s, %s, %L, %s)',
                       p_product_id, p_store_id, p_quantity, 'POS', v_txn_id))
         AS r(success BOOLEAN, reason TEXT);

    -- 3. Save the answer
    IF v_success THEN
        UPDATE pos_transaction SET transaction_status = 'APPROVED'
        WHERE pos_transaction.transaction_id = v_txn_id;
        INSERT INTO pos_payment (transaction_id, payment_method, payment_amount, payment_status)
        VALUES (v_txn_id, 'CARD', v_total, 'APPROVED');
        INSERT INTO pos_receipts (transaction_id, receipt_number, delivery_method)
        VALUES (v_txn_id, 'RC-' || lpad(v_txn_id::TEXT, 8, '0'), 'PRINTED');
    ELSE
        UPDATE pos_transaction SET transaction_status = 'REJECTED', rejection_reason = v_reason
        WHERE pos_transaction.transaction_id = v_txn_id;
    END IF;

    RETURN QUERY
    SELECT t.transaction_id, t.transaction_status, t.rejection_reason
    FROM pos_transaction t WHERE t.transaction_id = v_txn_id;
END $$;